#!/usr/bin/env python3
#: asked-by: Henri, 2026-08-27 — "make a checker for the tend-sheets.html"
"""tools/sheets.py — the printable twin says what the sheets say, or this says where it does not.

    python3 tools/sheets.py            check doc/summary/tend-sheets.html against rules.md and interfaces.md
    python3 tools/sheets.py --root D   the same, for the tree at D (tests)

`doc/summary/` holds two sheets as markdown — the canonical text — and
one HTML file that renders both for print, regenerated by hand.  Until
2026-08-27 nothing held the two together: `test_summary.py` checked the
markdown's citations and its one live claim, and the HTML could say
"not built yet" for a week after the card closed (it did, for an hour:
doc/kaizen/2026-08-27-1714.md).  Prose cannot be graded for truth, so
this checks what can be checked, on both sides:

* **Headings.**  Every `## ` heading in a sheet (its text before any
  parenthesis) appears in the twin's visible text.  A section the twin
  dropped, or renamed, is red.
* **Names.**  Every tree file or card a sheet names in backticks —
  `tools/x.sh`, `node/x.py`, `.claude/settings.json`, `card:x.md`; the
  first word of the span, so `tools/fence.sh --restore` names
  `tools/fence.sh` — appears in the twin's text, and every such name in
  the twin's `<code>` appears in a sheet.  The twin's `where` spans
  name a tool by its basename (`fence.sh`), and a whole-word basename
  counts; a card must be named in full.  Directories (`board/`) and
  globs (`node/*.state`, `<date>`) are not names and are skipped.
* **Cards.**  Every `card:x.md` on either side resolves on some shelf
  (board/, done/, later/), and a chip that says `card:x.md · done` or
  `· blocked` beside it agrees with the card's status.

Exit 0 when the twin says what the sheets say; 1 with the lines that
differ; 2 on a bad argument.  Run at the gate by `test_summary.py`.
"""
import html
import pathlib
import re
import subprocess
import sys

NAME = re.compile(r"^(tools/|node/|spec/|test/|doc/|\.claude/|card:)[\w./-]+$")


def visible_text(page):
    page = re.sub(r"<(script|style)[^>]*>.*?</\1>", " ", page, flags=re.S)
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", page)))


def names_in(spans):
    """The tree files and cards among backtick/<code> spans: first word,
    whitespace collapsed; no directories, no globs."""
    out = set()
    for s in spans:
        tok = " ".join(s.split()).split(" ")[0] if s.strip() else ""
        if tok.endswith("/") or "*" in tok or "<" in tok or not NAME.match(tok):
            continue
        out.add(tok)
    return out


def card_status(root, name):
    for shelf in ("", "done/", "later/"):
        p = root / "board" / shelf / name
        if p.is_file():
            m = re.search(r"^    status +(\w+)", p.read_text(encoding="utf-8"), re.M)
            return shelf.rstrip("/") or "open", (m.group(1) if m else "?")
    return None, None


def check(root):
    summary = root / "doc" / "summary"
    sheets = [summary / "rules.md", summary / "interfaces.md"]
    twin = summary / "tend-sheets.html"
    lines, fail = [], False

    def say(ok, msg):
        nonlocal fail
        lines.append(f"  {'✓' if ok else '✗'} {msg}")
        fail = fail or not ok

    if not twin.is_file():
        say(False, f"{twin.relative_to(root)} is missing")
        return lines, True
    page = twin.read_text(encoding="utf-8")
    text = visible_text(page)
    low = text.lower()
    md = "\n".join(s.read_text(encoding="utf-8") for s in sheets if s.is_file())

    for s in sheets:
        for h in re.findall(r"^## (.+)$", s.read_text(encoding="utf-8"), re.M):
            head = re.split(r"\s+\(|\s+—\s+", h)[0].strip()
            say(head.lower() in low, f"heading “{head}” ({s.name}) is in the twin")

    md_names = names_in(re.findall(r"`([^`]+)`", md))
    twin_names = names_in(html.unescape(c) for c in re.findall(r"<code>([^<]*)</code>", page))
    def present(n, where):
        # the twin's `where` spans name a tool by basename (<b>fence.sh</b>);
        # a whole-word basename counts, a card must be named in full
        if n in where:
            return True
        base = n.rsplit("/", 1)[-1]
        return not n.startswith("card:") and re.search(r"(?<![\w/.-])" + re.escape(base) + r"(?![\w/-])", where) is not None
    for n in sorted(md_names):
        say(present(n, text), f"{n} — named by a sheet, in the twin")
    for n in sorted(twin_names - md_names):
        say(present(n, md), f"{n} — named by the twin, in a sheet")

    for n in sorted(set(re.findall(r"card:([\w-]+\.md)", md + text))):
        shelf, status = card_status(root, n)
        say(shelf is not None, f"card:{n} resolves on a shelf" + (f" ({shelf}, {status})" if shelf else ""))
    for n, word in re.findall(r"card:([\w-]+\.md)\s*·\s*(done|blocked|open|shelved)", text):
        shelf, status = card_status(root, n)
        agree = (word == "done" and shelf == "done") or (word != "done" and status == word)
        say(agree, f"the twin's chip says card:{n} is {word}; the card is {status} in {shelf}/")
    return lines, fail


def main(argv):
    root = pathlib.Path(__file__).resolve().parent.parent
    args = list(argv)
    if args[:1] == ["--root"] and len(args) == 2:
        root = pathlib.Path(args[1]).resolve()
    elif args in ([], ["--check"]):
        pass
    elif args in (["-h"], ["--help"]):
        print(__doc__.split("\n\n")[0]); return 0
    else:
        print(f"sheets: unknown argument {' '.join(args)!r}", file=sys.stderr); return 2
    lines, fail = check(root)
    print(f"sheets: doc/summary/tend-sheets.html against the two sheets ({root})\n")
    print("\n".join(lines))
    print("\n  " + ("the twin says what the sheets say." if not fail else "THE TWIN DIFFERS — the lines marked ✗ say where."))
    return 1 if fail else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
